# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-22 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmerecord',
            name='head_image',
            field=models.ImageField(default=1, upload_to='about_me/%Y/%m', verbose_name='\u6211\u7684\u5934\u50cf'),
            preserve_default=False,
        ),
    ]
