# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-22 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0002_aboutmerecord_head_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingsrecord',
            name='from_name',
            field=models.CharField(default='', max_length=66, verbose_name='\u662f\u8c01'),
        ),
    ]
