# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-22 11:16
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleSortRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u6587\u7ae0\u7c7b\u578b\u540d')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6587\u7ae0\u7c7b\u578b',
                'verbose_name_plural': '\u6587\u7ae0\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='ArticlesRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='articles_img/%Y/%m', verbose_name='\u6587\u7ae0\u5c01\u9762\u56fe')),
                ('name', models.CharField(max_length=100, verbose_name='\u6587\u7ae0\u540d')),
                ('content', DjangoUeditor.models.UEditorField(default='', verbose_name='\u5185\u5bb9')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('good_clicks', models.IntegerField(default=0, verbose_name='\u70b9\u8d5e\u6570')),
                ('comment_nums', models.IntegerField(default=0, verbose_name='\u8bc4\u8bba\u6570')),
                ('sort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles_manage.ArticleSortRecord', verbose_name='\u6587\u7ae0\u6240\u5c5e')),
            ],
            options={
                'verbose_name': '\u6587\u7ae0',
                'verbose_name_plural': '\u6587\u7ae0',
            },
        ),
    ]
