# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-22 11:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendCommentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='\u53d1\u9001\u8005\u540d\u5b57')),
                ('image', models.CharField(max_length=66, verbose_name='\u5934\u50cf')),
                ('comment', models.CharField(max_length=200, verbose_name='\u7559\u8a00')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('from_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles_manage.ArticlesRecord', verbose_name='\u6240\u5c5e\u6587\u7ae0')),
            ],
            options={
                'verbose_name': '\u8bc4\u8bba\u4fe1\u606f',
                'verbose_name_plural': '\u8bc4\u8bba\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='SendMessageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='\u53d1\u9001\u8005\u540d\u5b57')),
                ('image', models.CharField(max_length=66, verbose_name='\u5934\u50cf')),
                ('message', models.CharField(max_length=200, verbose_name='\u7559\u8a00')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7559\u8a00\u4fe1\u606f',
                'verbose_name_plural': '\u7559\u8a00\u4fe1\u606f',
            },
        ),
    ]
