# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-24 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendcommentrecord',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='\u4e2a\u4eba\u7f51\u7ad9'),
        ),
        migrations.AddField(
            model_name='sendcommentrecord',
            name='email',
            field=models.CharField(default='', max_length=100, verbose_name='\u90ae\u7bb1'),
        ),
        migrations.AddField(
            model_name='sendmessagerecord',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='\u4e2a\u4eba\u7f51\u7ad9'),
        ),
        migrations.AddField(
            model_name='sendmessagerecord',
            name='email',
            field=models.CharField(default='', max_length=100, verbose_name='\u90ae\u7bb1'),
        ),
    ]
