# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-22 11:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoShowRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('banner', '\u8f6e\u64ad\u56fe\u5c55\u793a'), ('scenery', '\u98ce\u666f\u56fe\u5c55\u793a'), ('photos', '\u56fe\u7247\u5899\u5c55\u793a')], default='photos', max_length=66, verbose_name='\u56fe\u7247\u7c7b\u578b')),
                ('image', models.ImageField(upload_to='photos/%Y/%m', verbose_name='\u597d\u770b\u7684\u56fe\u7247')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u56fe\u7247\u5b58\u50a8',
                'verbose_name_plural': '\u56fe\u7247\u5b58\u50a8',
            },
        ),
    ]
