# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-22 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoshowrecord',
            name='image_type',
            field=models.CharField(choices=[('banner', '\u8f6e\u64ad\u56fe\u5c55\u793a'), ('scenery', '\u98ce\u666f\u56fe\u5c55\u793a'), ('photos', '\u56fe\u7247\u5899\u5c55\u793a'), ('headImg', '\u5934\u50cf')], default='photos', max_length=66, verbose_name='\u56fe\u7247\u7c7b\u578b'),
        ),
    ]
